// <auto-generated />
using System;
using MedicalReports.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalReports.Migrations
{
    [DbContext(typeof(MedicalDataContext))]
    partial class MedicalDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalData.Data.Entities.BloodworkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodPressureDiastolic")
                        .HasColumnType("int");

                    b.Property<int>("BloodPressureSystolic")
                        .HasColumnType("int");

                    b.Property<int>("BloodSugar")
                        .HasColumnType("int");

                    b.Property<int>("CholesterolHdl")
                        .HasColumnType("int");

                    b.Property<int>("CholesterolLdl")
                        .HasColumnType("int");

                    b.Property<int>("CholesterolTotal")
                        .HasColumnType("int");

                    b.Property<int>("MedicalDataId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalDataId")
                        .IsUnique();

                    b.ToTable("Bloodwork");
                });

            modelBuilder.Entity("MedicalData.Data.Entities.ClientEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MedicalData.Data.Entities.GuidelineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BloodPressureNeedsAttentionDiastolic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressureNeedsAttentionSystolic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressureOptimalDiastolic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressureOptimalSystolic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressureSeriousIssueDiastolic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressureSeriousIssueSystolic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodSugarNeedsAttention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodSugarOptimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodSugarSeriousIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CholesterolHdlNeedsAttention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CholesterolHdlOptimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CholesterolHdlSeriousIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CholesterolLdlNeedsAttention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CholesterolLdlOptimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CholesterolLdlSeriousIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CholesterolTotalNeedsAttention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CholesterolTotalOptimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CholesterolTotalSeriousIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DietQualityNeedsAttention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DietQualityOptimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DietQualitySeriousIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseWeeklyMinutesNeedsAttention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseWeeklyMinutesOptimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseWeeklyMinutesSeriousIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SleepQualityNeedsAttention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SleepQualityOptimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SleepQualitySeriousIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StressLevelsNeedsAttention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StressLevelsOptimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StressLevelsSeriousIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guidelines");
                });

            modelBuilder.Entity("MedicalData.Data.Entities.MedicalDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("MedicalData");
                });

            modelBuilder.Entity("MedicalData.Data.Entities.QuestionaireEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DietQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExerciseWeeklyMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MedicalDataId")
                        .HasColumnType("int");

                    b.Property<string>("SleepQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StressLevels")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicalDataId")
                        .IsUnique();

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("MedicalData.Data.Entities.BloodworkEntity", b =>
                {
                    b.HasOne("MedicalData.Data.Entities.MedicalDataEntity", "MedicalData")
                        .WithOne("Bloodwork")
                        .HasForeignKey("MedicalData.Data.Entities.BloodworkEntity", "MedicalDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalData");
                });

            modelBuilder.Entity("MedicalData.Data.Entities.MedicalDataEntity", b =>
                {
                    b.HasOne("MedicalData.Data.Entities.ClientEntity", "Client")
                        .WithOne("MedicalData")
                        .HasForeignKey("MedicalData.Data.Entities.MedicalDataEntity", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MedicalData.Data.Entities.QuestionaireEntity", b =>
                {
                    b.HasOne("MedicalData.Data.Entities.MedicalDataEntity", "MedicalData")
                        .WithOne("Questionnaire")
                        .HasForeignKey("MedicalData.Data.Entities.QuestionaireEntity", "MedicalDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalData");
                });

            modelBuilder.Entity("MedicalData.Data.Entities.ClientEntity", b =>
                {
                    b.Navigation("MedicalData");
                });

            modelBuilder.Entity("MedicalData.Data.Entities.MedicalDataEntity", b =>
                {
                    b.Navigation("Bloodwork");

                    b.Navigation("Questionnaire");
                });
#pragma warning restore 612, 618
        }
    }
}
